---

- name: download kernel
  apt:  name="linux-image-{{ kernel_version }}"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "16"
    - ansible_kernel != kernel_version

- name: change sysctl
  sysctl: name={{ item.name }} value={{ item.value }} reload=no
  with_items:
    - { name: net.core.default_qdisc,             value: fq  }
    - { name: net.ipv4.tcp_congestion_control,    value: bbr }
    - { name: net.ipv4.tcp_slow_start_after_idle, value: 0   }
