---
- include: resolvconf.yml
  when: ansible_os_family == 'Debian' and update_dns

- name: install packages
  package: name={{ vps_packages }} state=present

- name: install ubuntu specific packages
  package: name={{ ubuntu_packages }} state=present

- name: sysctl tweaks
  sysctl: name={{ item.key }} value={{ item.value }} reload=yes
  with_dict: "{{ sysctl_tweaks }}"

- name: ensure gai.conf exists
  file: path=/etc/gai.conf state=touch

- name: make ipv4 preferred by getaddrinfo
  lineinfile:
    name: /etc/gai.conf
    line: "precedence ::ffff:0:0/96  100"

- include: swap.yml

- include: bbr.yml
