---

- name: ensure resolvconf is not installed
  apt: name=resolvconf state=absent
  when: ansible_os_family == "Debian"

- name: Populate service facts
  service_facts:

- name: ensure systemd-resolved is disabled
  service: name=systemd-resolved enabled=no state=stopped
  when: ansible_facts.services['systemd-resolved.service'] is defined

- name: use fast DNS
  copy: dest=/etc/resolv.conf src=resolv.conf attr=i
