---

# not compatible with 2.0
# - name: pull image
#   docker_image: name="{{ image_url }}"

- name: make app dir
  file: path="{{ app_dir }}" state=directory

- name: copy files
  template: src="docker-compose.yml.j2" dest="{{ app_dir }}/docker-compose.yml"

- name: copy files
  template: src="deploy.sh.j2" dest="{{ app_dir }}/deploy.sh" mode=0750

- name: copy env file
  copy:
    src: "{{ env_file }}"
    dest: "{{ app_dir }}/{{ env_file }}"
    remote_src: yes

- name: copy hooks.json
  template: src=webhook.conf.j2 dest=/etc/webhook.conf
  notify: restart_webhook

- name: enable monit conf
  file:
    path=/etc/monit/conf-enabled/networking
    src=/etc/monit/conf-available/networking
    state=link
  notify: reload_monit

# - name: docker-compose build
#   shell: "cd {{ app_dir }}; docker-compose build"
#
# - name: docker-compose up
#   shell: "cd {{ app_dir }}; docker-compose up -d"
