ARG VER=18.04

FROM ubuntu:${VER}

ENV TZ=Australia/Brisbane

RUN apt-get update -y && \
  apt-get install -y --no-install-recommends openssh-server sudo && \
  sed -i -e 's/Defaults.*requiretty/#&/' /etc/sudoers && \
  sed -i -e 's/\(UsePAM \)yes/\1 no/' /etc/ssh/sshd_config && \
  mkdir -p /var/run/sshd && \
  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime

RUN useradd --create-home -s /bin/bash vagrant && \
  echo -n 'vagrant:vagrant' | chpasswd && \
  echo 'vagrant ALL = NOPASSWD: ALL' > /etc/sudoers.d/vagrant && \
  chmod 440 /etc/sudoers.d/vagrant && \
  mkdir -p /home/vagrant/.ssh && \
  chmod 700 /home/vagrant/.ssh && \
  echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ==" > /home/vagrant/.ssh/authorized_keys && \
  chmod 600 /home/vagrant/.ssh/authorized_keys && \
  chown -R vagrant:vagrant /home/vagrant/.ssh


EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
