---

- include: timezone.yml

- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: et.yml

- include: bash.yml

- include: vim.yml

- when: tame_zsh
  include: zsh.yml

- name: copy git config
  copy: src=gitconfig dest=~/.gitconfig

- name: reload local facts
  setup:
    filter: ansible_local
    fact_path: /root
