---

- name: disable firewalld
  service: name=firewalld state=stopped enabled=no 

- name: disable SELinux
  lineinfile:
    dest: /etc/selinux/config
    line: "SELinux=disabled"
    regexp: ^SELINUX=
