---
- name: check if motd-news exits
  stat: path=/etc/default/motd-news
  register: motd_news

- name: forbid motd-news to call home
  lineinfile:
    dest: /etc/default/motd-news
    line: "ENABLED=0"
    regexp: ^ENABLED=
  when: motd_news.stat.exists

- name: disable motd-news timer
  systemd:
    name: motd-news.timer
    state: stopped
    enabled: no

- name: disable unattended-upgrades download
  lineinfile:
    dest: /etc/apt/apt.conf.d/10periodic
    line: 'APT::Periodic::Download-Upgradeable-Packages "0";'
    regexp: ^APT::Periodic::Download-Upgradeable-Packages

- name: disable unattended-upgrades
  lineinfile:
    dest: /etc/apt/apt.conf.d/10periodic
    line: 'APT::Periodic::Unattended-Upgrade "0";'
    regexp: ^APT::Periodic::Unattended-Upgrade
