---
- name: install zsh
  package: name=zsh state=present
  become: yes

- name: copy configuration
  get_url:
    url: https://github.com/roylez/dotfiles/raw/master/shell/.zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    force: yes

- name: change default shell to zsh
  user: name={{ ansible_user_id }} shell=/usr/bin/zsh
  become: yes
