---

- name: install packages
  package:
    name:
      - monit
      - curl

- name: install notification script
  template: src=notify_telegram.sh.j2 dest=/usr/local/bin/notify_telegram.sh mode=0755

- name: enable service
  service: name=monit state=started enabled=yes

- name: copy monit confs
  template: src={{item}}.j2 dest={{ monit_dir }}/{{item}}
  with_items:
    - daemon-default
    - networking
    - disk
  notify: reload_monit

- name: make sure conf.d dir is loaded
  lineinfile:
    dest: "{{ monitrc }}"
    regexp: '^#?\s*include\s{{ monit_dir }}/\*$'
    line: "include {{ monit_dir }}/*"
  notify: reload_monit
