---

- name: install
  apt: name=monit

- name: enable service
  service: name=monit state=started enabled=yes

- name: copy networking monit conf
  template: src=networking.monit.j2 dest=/etc/monit/conf-available/networking
  notify: reload_monit

- name: enable netowrking monitoring
  file:
    src:   /etc/monit/conf-available/networking
    dest:  /etc/monit/conf-enabled/networking
    state: link
  notify: reload_monit

- name: copy deamon defaults
  copy: src=daemon-default dest=/etc/monit/conf.d/daemon-default
  notify: reload_monit

- name: make sure conf.d dir is loaded
  lineinfile:
    dest: /etc/monit/monitrc
    regexp: '^#?\s*include\s/etc/monit/conf.d/\*$'
    line: include /etc/monit/conf.d/*
  notify: reload_monit

- name: make sure conf-enabled is loaded
  lineinfile:
    dest: /etc/monit/monitrc
    regexp: '^#?\s*include\s/etc/monit/conf-enabled/\*$'
    line: include /etc/monit/conf-enabled/*
  notify: reload_monit
