
package: "nomad_{{ version }}_linux_amd64.zip"

url: "https://releases.hashicorp.com/nomad/{{ version }}/{{ package }}"

is_server: "{{ nomad_server or ( ansible_local.role.nomad.server | default('fasle') == 'true' ) }}"
is_client: "{{ ansible_local.role.nomad.client | default('true') }}"
