
nomad_architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"

package: "nomad_{{ version }}_linux_{{ nomad_architecture }}.zip"

url: "https://releases.hashicorp.com/nomad/{{ version }}/{{ package }}"

is_server: "{{ nomad_server or ( ansible_local |json_query('role.nomad.server') == 'true' ) }}"
is_client: "{{ ansible_local |json_query('role.nomad.client') != 'false' }}"

client_meta: "{{ ansible_local.role.nomad_client_meta if (ansible_local |json_query('role.nomad_client_meta') is mapping) else {} }}"

nomad_datacenter: "{{ ansible_local.role.nomad.datacenter if (ansible_local |json_query('role.nomad.datacenter') != '') else default_datacenter }}"

cni_package: "cni-plugins-linux-{{ nomad_architecture }}-v{{cni_version}}.tgz"
cni_url: "https://github.com/containernetworking/plugins/releases/download/v{{cni_version}}/{{cni_package}}"
