
consul_architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"

package: "consul_{{ version }}_linux_{{ consul_architecture }}.zip"

url: "https://releases.hashicorp.com/consul/{{ version }}/{{ package }}"

is_server: "{{ consul_server or ( ansible_local |json_query('role.consul.server') == 'true' ) }}"

consul_datacenter: "{{ default_datacenter }}"

