---

- name: Insure `iptables` is installed
  package: name={{ item }} state=present
  with_items:
    - iptables
    - iptables-persistent
    - netfilter-persistent

- name: update iptables rules
  copy:
    src: rules.v4
    dest: /etc/iptables/rules.v4
  register: iptables_rules

- name: reload iptables rules
  when: iptables_rules.changed
  command: netfilter-persistent reload
