---

- name: Insure `iptables` is installed
  package: name={{ item }} state=present
  with_items:
    - iptables
    - iptables-persistent

# https://javapipe.com/blog/iptables-ddos-protection/
- name: iptables DDos mangle Rules
  iptables_raw:
    name: DDoS protection mangle
    table: mangle
    rules: |
      -A PREROUTING -m conntrack --ctstate INVALID -j DROP
      -A PREROUTING -p tcp ! --syn -m conntrack --ctstate NEW -j DROP
      -A PREROUTING -p tcp -m conntrack --ctstate NEW -m tcpmss ! --mss 536:65535 -j DROP
      -A PREROUTING -p tcp -m tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG NONE -j DROP
      -A PREROUTING -p tcp -m tcp --tcp-flags FIN,SYN FIN,SYN -j DROP
      -A PREROUTING -p tcp -m tcp --tcp-flags SYN,RST SYN,RST -j DROP
      -A PREROUTING -p tcp -m tcp --tcp-flags FIN,RST FIN,RST -j DROP
      -A PREROUTING -p tcp -m tcp --tcp-flags FIN,ACK FIN -j DROP
      -A PREROUTING -p tcp -m tcp --tcp-flags ACK,URG URG -j DROP
      -A PREROUTING -p tcp -m tcp --tcp-flags FIN,ACK FIN -j DROP
      -A PREROUTING -p tcp -m tcp --tcp-flags PSH,ACK PSH -j DROP
      -A PREROUTING -p tcp -m tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG FIN,SYN,RST,PSH,ACK,URG -j DROP
      -A PREROUTING -p tcp -m tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG NONE -j DROP
      -A PREROUTING -p tcp -m tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG FIN,PSH,URG -j DROP
      -A PREROUTING -p tcp -m tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG FIN,SYN,PSH,URG -j DROP
      -A PREROUTING -p tcp -m tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG FIN,SYN,RST,ACK,URG -j DROP
      -A PREROUTING -f -j DROP

- name: iptables DDos filter Rules
  iptables_raw:
    name: DDoS protection filter
    rules: |
      -A INPUT -p tcp -m connlimit --connlimit-above 111 -j REJECT --reject-with tcp-reset
      -A INPUT -p tcp -m tcp --tcp-flags RST RST -m limit --limit 2/sec --limit-burst 2 -j ACCEPT
      -A INPUT -p tcp -m tcp --tcp-flags RST RST -j DROP
      -A INPUT -p tcp -m conntrack --ctstate NEW -m limit --limit 60/sec --limit-burst 20 -j ACCEPT
      -A INPUT -p tcp -m conntrack --ctstate NEW -j DROP

- name: iptables SSH brute-force protection
  iptables_raw:
    name: ssh brute-force protection
    rules: |
      -A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -m recent --set --name DEFAULT --mask 255.255.255.255 --rsource
      -A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -m recent --update --seconds 60 --hitcount 10 --name DEFAULT --mask 255.255.255.255 --rsource -j DROP
