---
# http://www.codelitt.com/blog/my-first-10-minutes-on-a-server-primer-for-securing-ubuntu/

- name: install stuff
  apt: name={{ packages }}

- name: enable apt unattended security update
  copy: src={{ item }} dest=/etc/apt/apt.conf.d/
  with_items: [ 10periodic, 50unattended-upgrades ]

- name: update sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "{{ item.key }} {{ item.value }}"
    regexp: ^{{ item.key }}\s+
  with_dict: "{{ sshd_options }}"
  notify: restart_sshd

- name: remove black listed packages
  apt: name={{ remove_packages }} state=absent
  when: ansible_distribution == "Ubuntu"

- include: user.yml

