---

user_groups:
  - adm
  - ssh-user
user_shell:      /usr/bin/zsh
user_gh_nick:    roylez

sshd_options:
  Port:                   22
  ClientAliveInterval:    60
  PasswordAuthentication: "no"
  PubkeyAuthentication:   "yes"
  PermitRootLogin:        "no"
  AllowGroups:            ssh-user

packages:
  - fail2ban

remove_packages:
  - snapd
  - postfix
