user: roy

swarm_token:         "{{ vault_swarm_token         }}"
swarm_manager_token: "{{ vault_swarm_manager_token }}"
swarm_server:        "{{ vault_swarm_server        }}"

gitlab_user:     "{{ vault_gitlab_user }}"
gitlab_password: "{{ vault_gitlab_password }}"

cloak_image_url: "{{ vault_cloak_image_url }}"

ssh_key_name:    id_ed25519
ssh_private_key: "{{ vault_ssh_private_key }}"
ssh_public_key:  "{{ vault_ssh_public_key  }}"

nomad_ca:   "{{ vault_nomad_ca }}"
nomad_cert: "{{ vault_nomad_cert }}"
nomad_key:  "{{ vault_nomad_key }}"
