---

- name: download binary
  get_url:
    url: "{{ restic_release_url }}"
    dest: "/root/tmp"

- name: unpack
  command: bzip2 -d /root/tmp/{{ restic_package_name }}.bz2
  args:
    creates: /root/tmp/{{ restic_package_name }}

- name: install
  copy:
    src: /root/tmp/{{ restic_package_name }}
    dest: /usr/local/bin/restic
    remote_src: yes
    mode: 0700

- name: install completion
  command: restic generate --zsh-completion {{ ansible_env.HOME }}/.zfunctions/_restic
