---

- name: download
  get_url:
    url: "{{ release_url }}"
    dest: /root

- name: unpack
  unarchive:
    src: /root/{{ package_name }}.tar.gz
    dest: /root/tmp/{{ package_name }}
    remote_src: yes
    exclude:
      - README.md
      - LICENSE
    creates: /root/tmp/{{ package_name }}/kopia

- name: install
  copy:
    remote_src: yes
    src: /root/tmp/{{ package_name }}/kopia
    dest: /usr/local/bin
    mode: 0755

- name: install completion
  shell: /usr/local/bin/kopia --completion-script-zsh > _kopia
  args:
    chdir: "{{ ansible_env.HOME }}/.zfunctions"
    creates: _kopia

- name: set global compression policy
  when: kopia_installed.changed
  command: /usr/local/bin/kopia policy set --global --compression zstd
