- name: check if is already in swarm mode
  shell: "docker info -f '{{ '{{' }}.Swarm.LocalNodeState{{ '}}' }}'|grep -E '^active'"
  ignore_errors: yes
  register: swarm_active

- name: join swarm
  command: docker swarm join --token {{ token }} --advertise-addr {{ advertise_addr }} {{ manager }}
  ignore_errors: yes
  when: swarm_active.rc != 0
