---

- name: uninstall webhook deb
  apt: name=webhook state=absent

- name: download from github release
  get_url:
    url: "{{ webhook_package_url }}"
    dest: "/root/"

- name: make dir for unpacking
  file: path=/root/tmp state=directory

- name: unpack
  unarchive:
    src: /root/{{ webhook_package_name }}.tar.gz
    dest: /root/tmp
    remote_src: yes

- name: install
  copy:
    remote_src: yes
    src: /root/tmp/{{ webhook_package_name }}/webhook
    dest: /usr/local/bin
    mode: 0755

- stat: path={{ webhook_service_file }}
  register: service_file

- name: unmask service file in systemd
  file:
    path={{ webhook_service_file }}
    state=absent
  when: service_file.stat.exists and service_file.stat.islnk

- name: install service
  template: src=webhook.service.j2 dest={{ webhook_service_file }}
  notify: systemd_daemon_reload

- name: remove service overrides
  file:
    path=/etc/systemd/system/webhook.service.d
    state=absent
  notify: systemd_daemon_reload

- name: enable webhook service
  command: systemctl enable webhook -f
