---

- name: download nomad
  get_url:
    url: "{{ nomad_url }}"
    dest: /root

- name: install
  unarchive:
    src: /root/{{ nomad_package }}
    dest: /usr/local/bin
    remote_src: yes

- name: make sure /etc/nomad exists
  file: path=/etc/nomad state=directory

- name: install systemd unit
  copy:
    src: nomad.service
    dest: /etc/systemd/system/nomad.service
  notify: systemd_reload

- name: install tls ca
  copy:
    content: "{{ nomad_ca }}"
    dest: /etc/nomad/ca.pem
  notify: restart_nomad

- name: install tls server cert
  when: nomad.server
  copy:
    content: "{{ nomad_server_cert }}"
    dest: /etc/nomad/server.pem
  notify: restart_nomad

- name: install tls server key
  when: nomad.server
  copy:
    content: "{{ nomad_server_key }}"
    dest: /etc/nomad/server-key.pem
  notify: restart_nomad

- name: install tls client cert
  when: not nomad.server
  copy:
    content: "{{ nomad_client_cert }}"
    dest: /etc/nomad/client.pem
  notify: restart_nomad

- name: install tls client key
  when: not nomad.server
  copy:
    content: "{{ nomad_client_key }}"
    dest: /etc/nomad/client-key.pem
  notify: restart_nomad

- name: install agent config
  template:
    src=agent.hcl.j2
    dest=/etc/nomad/agent.hcl
  notify: restart_nomad

- name: enable service
  service: name=nomad state=started enabled=yes
