---

- include: apt.yml
  when: ansible_os_family == "Debian"

- include: yum.yml
  when: ansible_os_family == "RedHat"

- name: install docker
  package: name=docker-ce state=latest

# - name: install docker_py
#   package: name=python-docker
#   when: ansible_os_family == "Debian"

# aufs no more supported for Linux 4.0.x
- name: delete aufs
  file: path=/var/lib/docker/aufs state=absent

- name: ensure /etc/docker exists
  file: path=/etc/docker state=directory

- name: config docker daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: reload_docker

- name: start docker daemon
  service: name=docker state=started enabled=yes

- name: copy docker clean up script
  copy: src=docker_clean.sh dest=/usr/local/bin/docker-clean mode=0755

- name: create cron job to clean
  cron:
    name: "docker cleanup"
    minute: 13
    job: /usr/local/bin/docker-clean

- name: append docker group to user
  user: name={{ user }} groups=docker append=yes

- name: create network for tailscale
  when: ansible_tailscale0 is defined and create_tailscale_network
  docker_network:
    name: tailscale
    driver_options:
      com.docker.network.bridge.host_binding_ipv4: "{{ ansible_tailscale0.ipv4.address }}"

# - include: compose.yml
#   when: ansible_architecture == "x86_64"
