---

- include: apt.yml
  when: ansible_distribution == "Ubuntu"

- include: yum.yml
  when: ansible_distribution == "RedHat"

- name: install docker
  packge: name=docker-ce state=latest

- name: install docker_py
  package: name=python-docker

# aufs no more supported for Linux 4.0.x
- name: delete aufs
  file: path=/var/lib/docker/aufs state=absent

- name: config docker daemon
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify: reload_docker

- name: start docker daemon
  service: name=docker state=started enabled=yes

- name: check if docker-compose is installed
  shell: command -v docker-compose >/dev/null 2>&1
  register: docker_compose_installed
  ignore_errors: yes

- name: check if docker_compose version is {{ docker_compose_version }}
  shell: command docker-compose --version |grep {{ docker_compose_version }}
  register: docker_compose_up_to_date
  ignore_errors: yes
  when: docker_compose_installed.rc == 0

- name: install docker-compose
  get_url:
    dest: /usr/local/bin/docker-compose
    url:  "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    force: yes
    mode: 0755
  when: docker_compose_installed.rc !=0 or docker_compose_up_to_date.rc != 0

- name: ensure zfunctions exists
  file: path={{ ansible_env.HOME }}/.zfunctions state=directory

- name: install docker-compose completions
  get_url:
    dest: "{{ ansible_env.HOME }}/.zfunctions/_docker_compose"
    url:  https://github.com/docker/compose/raw/master/contrib/completion/zsh/_docker-compose

- name: copy docker clean up script
  copy: src=docker_clean.sh dest=/usr/local/bin/docker-clean mode=0755

- name: create cron job to clean
  cron:
    name: "docker cleanup"
    minute: 13
    job: /usr/local/bin/docker-clean
