---

- name: install apt-transport-https
  apt: name=apt-transport-https

- name: add docker apt-key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

- name: add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
  register: docker_repo_added

- name: refresh apt cache
  when: docker_repo_added.changed
  apt: update_cache=yes

- name: install docker
  apt: name=docker-ce state=present

# aufs no more supported for Linux 4.0.x
- name: delete aufs
  file: path=/var/lib/docker/aufs state=absent

- name: config docker daemon
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify: reload_docker

- name: start docker daemon
  service: name=docker state=started enabled=yes

- name: check if docker-compose is installed
  shell: command -v docker-compose >/dev/null 2>&1
  register: docker_compose_installed
  ignore_errors: yes

- name: check if docker_compose version is {{ docker_compose_version }}
  shell: command docker-compose --version |grep {{ docker_compose_version }}
  register: docker_compose_up_to_date
  ignore_errors: yes
  when: docker_compose_installed.rc == 0

- name: install docker-compose
  get_url:
    dest: /usr/local/bin/docker-compose
    url:  "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    force: yes
    mode: 0755
  when: docker_compose_installed.rc !=0 or docker_compose_up_to_date.rc != 0

- name: ensure zfunctions exists
  file: path={{ ansible_env.HOME }}/.zfunctions state=directory

- name: install docker-compose completions
  get_url:
    dest: "{{ ansible_env.HOME }}/.zfunctions/_docker_compose"
    url:  https://github.com/docker/compose/raw/master/contrib/completion/zsh/_docker-compose

- name: copy docker clean up script
  copy: src=docker_clean.sh dest=/usr/local/bin/docker-clean mode=0755

- name: create cron job to clean
  cron:
    name: "docker cleanup"
    minute: 13
    job: /usr/local/bin/docker-clean

- name: install docker_py
  apt: name=python-docker
